### PR TITLE
Add filter to background image

### PR DESCRIPTION
**Pull request by NickWu007**
Added a filter to the background image so it doesn't look as jarring.

Compare:

Before:

screenshot_2018-07-31 trylinks 1

After:
screenshot_2018-07-31 trylinks

### CODE REVIEW

**Comment by Arcadius19** [comment]
It seems quite dim now. Shouldn't it be slightly brighter?

**Comment by Arcadius19** [comment]
Never mind, it's just ma laptop screen is not the best. I checked it with the highest brightness and it looks good.

**Comment by NickWu007** [comment]
My feeling is the background should be dim enough, so that the content of screen is highlighted by contrast.

@jamescheney any opinion on this?

**Review by Arcadius19 — APPROVED** [review]

**Comment by NickWu007** [comment]
Will wait and see if James has any objection. If not I will merge soon.

**Comment by jamescheney** [comment]
This looks OK to me, I agree having bright blue buttons/links against a partly bright blue background is not ideal.

**Review by jamescheney — APPROVED** [review]

**Pull request merged**
