### PR TITLE
Flexible tutorials

### PR DESCRIPTION
**Pull request by Arcadius19**
Tutorials' descriptions and titles are dynamically fetched from the server through tutorial API.
Added an Admin component which is an interface to add a new tutorial - accessible only for admins.

### CODE REVIEW

**Comment by NickWu007** [comment]
Would you mind attaching screenshots of updated pages?

**Comment by Arcadius19** [comment]
screenshot from 2018-07-26 11-23-42
screenshot from 2018-07-26 11-26-52
screenshot from 2018-07-26 11-27-05
screenshot from 2018-07-26 11-27-18

**Comment by NickWu007** [comment]
I suggest putting headers to describe the 2 main areas. Just showing 2 `textarea`s  is a bit confusing. Everything else looks good.

**Comment by Arcadius19** [comment]
For now, textareas have initial placeholders describing their function, but I can add the headers too.

screenshot from 2018-07-26 11-22-54

**Comment by NickWu007** [comment]
I still think putting headers are necessary, since the placeholders disappears as soon as you type something, that one can accidentally enter the content reversed without noticing.

**Comment by NickWu007** [comment]
@Arcadius19  Ping

**Comment by Arcadius19** [comment]
screenshot from 2018-07-27 11-29-02

**Comment by NickWu007** [comment]
LGTM. Please merge.

**Comment by Arcadius19** [comment]
Sorry, been busy with setting everything up on my laptop, plus there was a fire alarm here yesterday.

**Pull request merged**
